### ISSUE TITLE
Not lucky when installing...

### ISSUE THREAD

**Issue by affonso** [totaljs/openplatform#1]
I tried install (in a rush) and:

`C:\...\Projetos\openplatform-master> node .\debug.js`

```
{ Error: Cannot find module 'total.js/utils'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at app (C:\Users\Daniel\Projetos\openplatform-master\debug.js:11:2863)
    at run (C:\Users\Daniel\Projetos\openplatform-master\debug.js:11:3925)
    at Object.<anonymous> (C:\Users\Daniel\Projetos\openplatform-master\debug.js:11:4193)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32) code: 'MODULE_NOT_FOUND' }
```

**Comment by molda** [comment]
Please run `npm install total.js@latest` before `node debug.js`

**Comment by affonso** [comment]
Perfect! Tks.

**Comment by petersirka** [comment]
We'll prepare better docs and examples.
Thanks!
